-- MySQL Script generated by MySQL Workbench
-- Вск 28 Июл 2019 14:08:29
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema service
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema service
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `service` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema service
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema service
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `service` DEFAULT CHARACTER SET utf8 ;
USE `service` ;

-- -----------------------------------------------------
-- Table `service`.`tTypeOperation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service`.`tTypeOperation` (
  `idtType` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`idtType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `service`.`tProductOvner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service`.`tProductOvner` (
  `idProductOvner` INT(11) NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NULL DEFAULT NULL,
  `lastName` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idProductOvner`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `service`.`tItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service`.`tItem` (
  `idItem` INT(11) NOT NULL AUTO_INCREMENT,
  `count` INT(11) NULL DEFAULT NULL,
  `price` DECIMAL(6,2) UNSIGNED ZEROFILL NULL DEFAULT NULL,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  `idProductOvner` INT(11) NOT NULL,
  `dateAdd` DATETIME NULL,
  PRIMARY KEY (`idItem`, `idProductOvner`),
  INDEX `fk_tItem_tProductOvner1_idx` (`idProductOvner` ASC),
  CONSTRAINT `fk_tItem_tProductOvner1`
    FOREIGN KEY (`idProductOvner`)
    REFERENCES `service`.`tProductOvner` (`idProductOvner`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `service`.`tOperation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service`.`tOperation` (
  `idOperation` INT NOT NULL,
  `idItem` INT(11) NOT NULL,
  `idtType` INT NOT NULL,
  `count` INT NULL,
  `price` DECIMAL(6,2) NULL,
  `DateOperation` DATETIME NULL,
  PRIMARY KEY (`idOperation`, `idItem`, `idtType`),
  INDEX `fk_tOperation_tTypeOperation_idx` (`idtType` ASC),
  INDEX `fk_tOperation_tItem1_idx` (`idItem` ASC),
  CONSTRAINT `fk_tOperation_tTypeOperation`
    FOREIGN KEY (`idtType`)
    REFERENCES `service`.`tTypeOperation` (`idtType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tOperation_tItem1`
    FOREIGN KEY (`idItem`)
    REFERENCES `service`.`tItem` (`idItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `service` ;

-- -----------------------------------------------------
-- Table `service`.`tCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service`.`tCategory` (
  `idCategory` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idCategory`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `service`.`tCategory_has_tItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service`.`tCategory_has_tItem` (
  `idCategory` INT(11) NOT NULL,
  `idItem` INT(11) NOT NULL,
  PRIMARY KEY (`idCategory`, `idItem`),
  INDEX `fk_tCategory_has_tItem_tItem1_idx` (`idItem` ASC),
  INDEX `fk_tCategory_has_tItem_tCategory_idx` (`idCategory` ASC),
  CONSTRAINT `fk_tCategory_has_tItem_tCategory`
    FOREIGN KEY (`idCategory`)
    REFERENCES `service`.`tCategory` (`idCategory`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tCategory_has_tItem_tItem1`
    FOREIGN KEY (`idItem`)
    REFERENCES `service`.`tItem` (`idItem`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `service`.`tContact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service`.`tContact` (
  `privateEmail` VARCHAR(45) NULL DEFAULT NULL,
  `workEmail` VARCHAR(45) NULL DEFAULT NULL,
  `workPhone` VARCHAR(45) NULL DEFAULT NULL,
  `privatePhone` VARCHAR(45) NULL DEFAULT NULL,
  `idProductOvner` INT(11) NOT NULL,
  `company` VARCHAR(45) NULL DEFAULT NULL,
  `idContact` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idContact`),
  UNIQUE INDEX `private_email_UNIQUE` (`privateEmail` ASC),
  INDEX `fk_tContact_1_idx` (`idProductOvner` ASC),
  CONSTRAINT `fk_tContact_1`
    FOREIGN KEY (`idProductOvner`)
    REFERENCES `service`.`tProductOvner` (`idProductOvner`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
